---
- name: enable the intranet service
  hosts: dev
  become: yes
  tasks:
    - name: instal https and  firewalld
      ansible.builtin.yum:
        name:
          - httpd
          - firewalld
        state: latest
    - name: firewalld enable 
      ansible.builtin.service: name=firewalld enabled=true state=started

    - name: httpd enabled and running
      ansible.builtin.service: name=httpd enabled=true state=started

    - name: copy the files
      ansible.builtin.copy: content="welcome the robo the world!\n" dest=/var/www/html/index.html

- name: test the internet
  hosts: local
  become: yes
  tasks:
    - name: connect to the intranet site
      ansible.builtin.uri:
        url: http://jenky
        status_code: 200
            
