---
- name: install the {{ package }} package
  ansible.builtin.yum:
    name: "{{ package }}"
    state: latest

- name: start the {{ service }} service.
  ansible.builtin.service:
      name: "{{ service }}"
      state: "{{ svc_state }}"
