---
- name: use the vhost roles
  hosts: dev
  become: yes

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration'

  roles:
    - myvhost

  post_tasks:
    - debug:
        msg:  'Web server has been configured.'
