- ansible.builtin.yum:
    name: "{{ extra_packages }}" 

- ansible.builtin.copy:
    src: /home/dendhiajr/playbook/dev-flowcontrol/my.cnf
    dest: "{{ configure_database_path }}"
    owner: dendhiajr
    group: dendhiajr
    mode: 0644
    force: yes

- ansible.builtin.service:
    name: "{{ db_service }}"
    state: started
    enabled: true
