---
- hosts: dev
  become: yes
  vars:
    system_owner: deepan.redhat@gmail.com
  tasks:
    - template:
        src:  motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
