---
- name: create user accounts for all our servers
  hosts: all
  become: true
  vars_files:
    - secret.yml
  tasks:
    - name: creating users from secret.yml
      user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items: "{{ newusers }}"
